{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "file is opened successfully\n"
     ]
    }
   ],
   "source": [
    "#opens the file file.txt in read mode    \n",
    "fileptr = open(\"Gaurav.txt\",\"r\")    \n",
    "    \n",
    "if fileptr:    \n",
    "    print(\"file opened successfully:)\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Ways to open and read the file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Day 6 was a short yet interesting. I delved into of error handling today. In Python programming, error handling holds significant importance as it ensures users understand issues encountered. These issues could range from incorrect data types inputted by users to other forms of input errors. Efficient error handling allows us to communicate these problems effectively. Moreover, since the interpreter stops code execution on encountering an error, we often need to instruct it to proceed if required. Thus, error handling becomes very important in Python coding.\n",
      "\n",
      "\n",
      "\n",
      "The major types of errors I came across were:\n",
      "\n",
      "\n",
      "\n",
      "Type error\n",
      "\n",
      "\n",
      "\n",
      "x = input(\"enter x \")\n",
      "\n",
      "y= int(input(\"enter y\"))\n",
      "\n",
      "\n",
      "\n",
      "try:\n",
      "\n",
      "  z = x+y\n",
      "\n",
      "  print(z)\n",
      "\n",
      "except TypeError:\n",
      "\n",
      "  print(\"Cannot add integer and string\")\n",
      "\n",
      "If the data type of input is identified to be something that canâ€™t be mutable with each other. The following error shows up.\n",
      "\n",
      "\n",
      "\n",
      "2. Index error â€” runtime error\n",
      "\n",
      "\n",
      "\n",
      "a = [1, 2, 3]\n",
      "\n",
      "try:\n",
      "\n",
      " print (\"Second element = %d\" %(a[1]))\n",
      "\n",
      "\n",
      "\n",
      " # Throws error since there are only 3 elements in array\n",
      "\n",
      " print (\"Fourth element = %d\" %(a[3]))\n",
      "\n",
      "\n",
      "\n",
      "except:\n",
      "\n",
      " print (\"An error occurred\")\n",
      "\n",
      "If the loop indexes out of the range of length of the current data set, this error pops up.\n",
      "\n",
      "\n",
      "\n",
      "3. Zero division error\n",
      "\n",
      "\n",
      "\n",
      "def func(n):\n",
      "\n",
      "  try:\n",
      "\n",
      "      a = 4/n\n",
      "\n",
      "      print(a)\n",
      "\n",
      "      print(d)\n",
      "\n",
      "  except ZeroDivisionError:\n",
      "\n",
      "      print(\"Division by zero not defined\")\n",
      "\n",
      "  except NameError:\n",
      "\n",
      "      print('Name not defined in the scope')\n",
      "\n",
      "  finally:\n",
      "\n",
      "      print(\"Operation completed\")\n",
      "\n",
      "func(0)\n",
      "\n",
      "func(2)\n",
      "\n",
      "Any science student would frown over zero division, and python does the same with this error.\n",
      "\n",
      "\n",
      "\n",
      "4. Name error\n",
      "\n",
      "\n",
      "\n",
      "def func(name):\n",
      "\n",
      "    try:\n",
      "\n",
      "        if name == 'Gaurav':\n",
      "\n",
      "            print('Hello,',name)\n",
      "\n",
      "        else:\n",
      "\n",
      "            raise NameError(name)\n",
      "\n",
      "    except NameError:\n",
      "\n",
      "\n",
      "\n",
      "        print('Access Denied:', name)\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "func('Gaurav')\n",
      "\n",
      "func('Tilak')\n",
      "\n",
      "When there is a call for something that has not been defined, the following error pops.\n",
      "\n",
      "\n",
      "\n",
      "5. Syntax error\n",
      "\n",
      "\n",
      "\n",
      "Anytime the syntax is wrong, this gets executed.\n",
      "\n",
      "\n",
      "\n",
      "With that we wrap a short day 6!\n",
      "\n",
      "Tomorrow!!!\n",
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "file = open('Gaurav.txt', 'r')\n",
    "\n",
    "for each in file:\n",
    "\tprint (each)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Day 6 was a short yet interesting. I delved into of error handling today. In Python programming, error handling holds significant importance as it ensures users understand issues encountered. These issues could range from incorrect data types inputted by users to other forms of input errors. Efficient error handling allows us to communicate these problems effectively. Moreover, since the interpreter stops code execution on encountering an error, we often need to instruct it to proceed if required. Thus, error handling becomes very important in Python coding.\n",
      "\n",
      "The major types of errors I came across were:\n",
      "\n",
      "Type error\n",
      "\n",
      "x = input(\"enter x \")\n",
      "y= int(input(\"enter y\"))\n",
      "\n",
      "try:\n",
      "  z = x+y\n",
      "  print(z)\n",
      "except TypeError:\n",
      "  print(\"Cannot add integer and string\")\n",
      "If the data type of input is identified to be something that canâ€™t be mutable with each other. The following error shows up.\n",
      "\n",
      "2. Index error â€” runtime error\n",
      "\n",
      "a = [1, 2, 3]\n",
      "try:\n",
      " print (\"Second element = %d\" %(a[1]))\n",
      "\n",
      " # Throws error since there are only 3 elements in array\n",
      " print (\"Fourth element = %d\" %(a[3]))\n",
      "\n",
      "except:\n",
      " print (\"An error occurred\")\n",
      "If the loop indexes out of the range of length of the current data set, this error pops up.\n",
      "\n",
      "3. Zero division error\n",
      "\n",
      "def func(n):\n",
      "  try:\n",
      "      a = 4/n\n",
      "      print(a)\n",
      "      print(d)\n",
      "  except ZeroDivisionError:\n",
      "      print(\"Division by zero not defined\")\n",
      "  except NameError:\n",
      "      print('Name not defined in the scope')\n",
      "  finally:\n",
      "      print(\"Operation completed\")\n",
      "func(0)\n",
      "func(2)\n",
      "Any science student would frown over zero division, and python does the same with this error.\n",
      "\n",
      "4. Name error\n",
      "\n",
      "def func(name):\n",
      "    try:\n",
      "        if name == 'Gaurav':\n",
      "            print('Hello,',name)\n",
      "        else:\n",
      "            raise NameError(name)\n",
      "    except NameError:\n",
      "\n",
      "        print('Access Denied:', name)\n",
      "\n",
      "\n",
      "func('Gaurav')\n",
      "func('Tilak')\n",
      "When there is a call for something that has not been defined, the following error pops.\n",
      "\n",
      "5. Syntax error\n",
      "\n",
      "Anytime the syntax is wrong, this gets executed.\n",
      "\n",
      "With that we wrap a short day 6!\n",
      "Tomorrow!!!\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "file = open('Gaurav.txt','r')\n",
    "print(file.read())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Day 6 was a short yet interesting. I delved into of error handling today. In Python programming, error handling holds significant importance as it ensures users understand issues encountered. These issues could range from incorrect data types inputted by users to other forms of input errors. Efficient error handling allows us to communicate these problems effectively. Moreover, since the interpreter stops code execution on encountering an error, we often need to instruct it to proceed if required. Thus, error handling becomes very important in Python coding.\n",
      "\n",
      "The major types of errors I came across were:\n",
      "\n",
      "Type error\n",
      "\n",
      "x = input(\"enter x \")\n",
      "y= int(input(\"enter y\"))\n",
      "\n",
      "try:\n",
      "  z = x+y\n",
      "  print(z)\n",
      "except TypeError:\n",
      "  print(\"Cannot add integer and string\")\n",
      "If the data type of input is identified to be something that canâ€™t be mutable with each other. The following error shows up.\n",
      "\n",
      "2. Index error â€” runtime error\n",
      "\n",
      "a = [1, 2, 3]\n",
      "try:\n",
      " print (\"Second element = %d\" %(a[1]))\n",
      "\n",
      " # Throws error since there are only 3 elements in array\n",
      " print (\"Fourth element = %d\" %(a[3]))\n",
      "\n",
      "except:\n",
      " print (\"An error occurred\")\n",
      "If the loop indexes out of the range of length of the current data set, this error pops up.\n",
      "\n",
      "3. Zero division error\n",
      "\n",
      "def func(n):\n",
      "  try:\n",
      "      a = 4/n\n",
      "      print(a)\n",
      "      print(d)\n",
      "  except ZeroDivisionError:\n",
      "      print(\"Division by zero not defined\")\n",
      "  except NameError:\n",
      "      print('Name not defined in the scope')\n",
      "  finally:\n",
      "      print(\"Operation completed\")\n",
      "func(0)\n",
      "func(2)\n",
      "Any science student would frown over zero division, and python does the same with this error.\n",
      "\n",
      "4. Name error\n",
      "\n",
      "def func(name):\n",
      "    try:\n",
      "        if name == 'Gaurav':\n",
      "            print('Hello,',name)\n",
      "        else:\n",
      "            raise NameError(name)\n",
      "    except NameError:\n",
      "\n",
      "        print('Access Denied:', name)\n",
      "\n",
      "\n",
      "func('Gaurav')\n",
      "func('Tilak')\n",
      "When there is a call for something that has not been defined, the following error pops.\n",
      "\n",
      "5. Syntax error\n",
      "\n",
      "Anytime the syntax is wrong, this gets executed.\n",
      "\n",
      "With that we wrap a short day 6!\n",
      "Tomorrow!!!\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "with open('Gaurav.txt', 'r') as file:\n",
    "    print(file.read())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Day 6 was a short ye\n"
     ]
    }
   ],
   "source": [
    "#reading by charecters - \" \" is a  charecter as well.\n",
    "\n",
    "with open('Gaurav.txt', 'r') as file:\n",
    "    print(file.read(20))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Day 6 was a short yet interesting. I delved into of error handling today. In Python programming, error handling holds significant importance as it ensures users understand issues encountered. These issues could range from incorrect data types inputted by users to other forms of input errors. Efficient error handling allows us to communicate these problems effectively. Moreover, since the interpreter stops code execution on encountering an error, we often need to instruct it to proceed if required. Thus, error handling becomes very important in Python coding.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#readline\n",
    "\n",
    "with open('Gaurav.txt', 'r') as file:\n",
    "    print(file.readline())\n",
    "\n",
    "file.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Day 6 was a short yet interesting. I delved into of error handling today. In Python programming, error handling holds significant importance as it ensures users understand issues encountered. These issues could range from incorrect data types inputted by users to other forms of input errors. Efficient error handling allows us to communicate these problems effectively. Moreover, since the interpreter stops code execution on encountering an error, we often need to instruct it to proceed if required. Thus, error handling becomes very important in Python coding.\n",
      "\n",
      "\n",
      "\n",
      "The major types of errors I came across were:\n",
      "\n",
      "\n",
      "\n",
      "Type error\n",
      "\n",
      "\n",
      "\n",
      "x = input(\"enter x \")\n",
      "\n",
      "y= int(input(\"enter y\"))\n",
      "\n",
      "\n",
      "\n",
      "try:\n",
      "\n",
      "  z = x+y\n",
      "\n",
      "  print(z)\n",
      "\n",
      "except TypeError:\n",
      "\n",
      "  print(\"Cannot add integer and string\")\n",
      "\n",
      "If the data type of input is identified to be something that canâ€™t be mutable with each other. The following error shows up.\n",
      "\n",
      "\n",
      "\n",
      "2. Index error â€” runtime error\n",
      "\n",
      "\n",
      "\n",
      "a = [1, 2, 3]\n",
      "\n",
      "try:\n",
      "\n",
      " print (\"Second element = %d\" %(a[1]))\n",
      "\n",
      "\n",
      "\n",
      " # Throws error since there are only 3 elements in array\n",
      "\n",
      " print (\"Fourth element = %d\" %(a[3]))\n",
      "\n",
      "\n",
      "\n",
      "except:\n",
      "\n",
      " print (\"An error occurred\")\n",
      "\n",
      "If the loop indexes out of the range of length of the current data set, this error pops up.\n",
      "\n",
      "\n",
      "\n",
      "3. Zero division error\n",
      "\n",
      "\n",
      "\n",
      "def func(n):\n",
      "\n",
      "  try:\n",
      "\n",
      "      a = 4/n\n",
      "\n",
      "      print(a)\n",
      "\n",
      "      print(d)\n",
      "\n",
      "  except ZeroDivisionError:\n",
      "\n",
      "      print(\"Division by zero not defined\")\n",
      "\n",
      "  except NameError:\n",
      "\n",
      "      print('Name not defined in the scope')\n",
      "\n",
      "  finally:\n",
      "\n",
      "      print(\"Operation completed\")\n",
      "\n",
      "func(0)\n",
      "\n",
      "func(2)\n",
      "\n",
      "Any science student would frown over zero division, and python does the same with this error.\n",
      "\n",
      "\n",
      "\n",
      "4. Name error\n",
      "\n",
      "\n",
      "\n",
      "def func(name):\n",
      "\n",
      "    try:\n",
      "\n",
      "        if name == 'Gaurav':\n",
      "\n",
      "            print('Hello,',name)\n",
      "\n",
      "        else:\n",
      "\n",
      "            raise NameError(name)\n",
      "\n",
      "    except NameError:\n",
      "\n",
      "\n",
      "\n",
      "        print('Access Denied:', name)\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "func('Gaurav')\n",
      "\n",
      "func('Tilak')\n",
      "\n",
      "When there is a call for something that has not been defined, the following error pops.\n",
      "\n",
      "\n",
      "\n",
      "5. Syntax error\n",
      "\n",
      "\n",
      "\n",
      "Anytime the syntax is wrong, this gets executed.\n",
      "\n",
      "\n",
      "\n",
      "With that we wrap a short day 6!\n",
      "\n",
      "Tomorrow!!!\n",
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#to read the file using readline\n",
    "\n",
    "file = open('Gaurav.txt','r')\n",
    "\n",
    "line = file.readline()\n",
    "\n",
    "while line:\n",
    "    print(line)\n",
    "    line= file.readline()\n",
    "\n",
    "file.close()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Day 6 was a short yet interesting. I delved into of error handling today. In Python programming, error handling holds significant importance as it ensures users understand issues encountered. These issues could range from incorrect data types inputted by users to other forms of input errors. Efficient error handling allows us to communicate these problems effectively. Moreover, since the interpreter stops code execution on encountering an error, we often need to instruct it to proceed if required. Thus, error handling becomes very important in Python coding.\\n', '\\n', 'The major types of errors I came across were:\\n', '\\n', 'Type error\\n', '\\n', 'x = input(\"enter x \")\\n', 'y= int(input(\"enter y\"))\\n', '\\n', 'try:\\n', '  z = x+y\\n', '  print(z)\\n', 'except TypeError:\\n', '  print(\"Cannot add integer and string\")\\n', 'If the data type of input is identified to be something that canâ€™t be mutable with each other. The following error shows up.\\n', '\\n', '2. Index error â€” runtime error\\n', '\\n', 'a = [1, 2, 3]\\n', 'try:\\n', ' print (\"Second element = %d\" %(a[1]))\\n', '\\n', ' # Throws error since there are only 3 elements in array\\n', ' print (\"Fourth element = %d\" %(a[3]))\\n', '\\n', 'except:\\n', ' print (\"An error occurred\")\\n', 'If the loop indexes out of the range of length of the current data set, this error pops up.\\n', '\\n', '3. Zero division error\\n', '\\n', 'def func(n):\\n', '  try:\\n', '      a = 4/n\\n', '      print(a)\\n', '      print(d)\\n', '  except ZeroDivisionError:\\n', '      print(\"Division by zero not defined\")\\n', '  except NameError:\\n', \"      print('Name not defined in the scope')\\n\", '  finally:\\n', '      print(\"Operation completed\")\\n', 'func(0)\\n', 'func(2)\\n', 'Any science student would frown over zero division, and python does the same with this error.\\n', '\\n', '4. Name error\\n', '\\n', 'def func(name):\\n', '    try:\\n', \"        if name == 'Gaurav':\\n\", \"            print('Hello,',name)\\n\", '        else:\\n', '            raise NameError(name)\\n', '    except NameError:\\n', '\\n', \"        print('Access Denied:', name)\\n\", '\\n', '\\n', \"func('Gaurav')\\n\", \"func('Tilak')\\n\", 'When there is a call for something that has not been defined, the following error pops.\\n', '\\n', '5. Syntax error\\n', '\\n', 'Anytime the syntax is wrong, this gets executed.\\n', '\\n', 'With that we wrap a short day 6!\\n', 'Tomorrow!!!\\n', '\\n']\n",
      "['Day', '6', 'was', 'a', 'short', 'yet', 'interesting.', 'I', 'delved', 'into', 'of', 'error', 'handling', 'today.', 'In', 'Python', 'programming,', 'error', 'handling', 'holds', 'significant', 'importance', 'as', 'it', 'ensures', 'users', 'understand', 'issues', 'encountered.', 'These', 'issues', 'could', 'range', 'from', 'incorrect', 'data', 'types', 'inputted', 'by', 'users', 'to', 'other', 'forms', 'of', 'input', 'errors.', 'Efficient', 'error', 'handling', 'allows', 'us', 'to', 'communicate', 'these', 'problems', 'effectively.', 'Moreover,', 'since', 'the', 'interpreter', 'stops', 'code', 'execution', 'on', 'encountering', 'an', 'error,', 'we', 'often', 'need', 'to', 'instruct', 'it', 'to', 'proceed', 'if', 'required.', 'Thus,', 'error', 'handling', 'becomes', 'very', 'important', 'in', 'Python', 'coding.']\n",
      "[]\n",
      "['The', 'major', 'types', 'of', 'errors', 'I', 'came', 'across', 'were:']\n",
      "[]\n",
      "['Type', 'error']\n",
      "[]\n",
      "['x', '=', 'input(\"enter', 'x', '\")']\n",
      "['y=', 'int(input(\"enter', 'y\"))']\n",
      "[]\n",
      "['try:']\n",
      "['z', '=', 'x+y']\n",
      "['print(z)']\n",
      "['except', 'TypeError:']\n",
      "['print(\"Cannot', 'add', 'integer', 'and', 'string\")']\n",
      "['If', 'the', 'data', 'type', 'of', 'input', 'is', 'identified', 'to', 'be', 'something', 'that', 'canâ€™t', 'be', 'mutable', 'with', 'each', 'other.', 'The', 'following', 'error', 'shows', 'up.']\n",
      "[]\n",
      "['2.', 'Index', 'error', 'â€”', 'runtime', 'error']\n",
      "[]\n",
      "['a', '=', '[1,', '2,', '3]']\n",
      "['try:']\n",
      "['print', '(\"Second', 'element', '=', '%d\"', '%(a[1]))']\n",
      "[]\n",
      "['#', 'Throws', 'error', 'since', 'there', 'are', 'only', '3', 'elements', 'in', 'array']\n",
      "['print', '(\"Fourth', 'element', '=', '%d\"', '%(a[3]))']\n",
      "[]\n",
      "['except:']\n",
      "['print', '(\"An', 'error', 'occurred\")']\n",
      "['If', 'the', 'loop', 'indexes', 'out', 'of', 'the', 'range', 'of', 'length', 'of', 'the', 'current', 'data', 'set,', 'this', 'error', 'pops', 'up.']\n",
      "[]\n",
      "['3.', 'Zero', 'division', 'error']\n",
      "[]\n",
      "['def', 'func(n):']\n",
      "['try:']\n",
      "['a', '=', '4/n']\n",
      "['print(a)']\n",
      "['print(d)']\n",
      "['except', 'ZeroDivisionError:']\n",
      "['print(\"Division', 'by', 'zero', 'not', 'defined\")']\n",
      "['except', 'NameError:']\n",
      "[\"print('Name\", 'not', 'defined', 'in', 'the', \"scope')\"]\n",
      "['finally:']\n",
      "['print(\"Operation', 'completed\")']\n",
      "['func(0)']\n",
      "['func(2)']\n",
      "['Any', 'science', 'student', 'would', 'frown', 'over', 'zero', 'division,', 'and', 'python', 'does', 'the', 'same', 'with', 'this', 'error.']\n",
      "[]\n",
      "['4.', 'Name', 'error']\n",
      "[]\n",
      "['def', 'func(name):']\n",
      "['try:']\n",
      "['if', 'name', '==', \"'Gaurav':\"]\n",
      "[\"print('Hello,',name)\"]\n",
      "['else:']\n",
      "['raise', 'NameError(name)']\n",
      "['except', 'NameError:']\n",
      "[]\n",
      "[\"print('Access\", \"Denied:',\", 'name)']\n",
      "[]\n",
      "[]\n",
      "[\"func('Gaurav')\"]\n",
      "[\"func('Tilak')\"]\n",
      "['When', 'there', 'is', 'a', 'call', 'for', 'something', 'that', 'has', 'not', 'been', 'defined,', 'the', 'following', 'error', 'pops.']\n",
      "[]\n",
      "['5.', 'Syntax', 'error']\n",
      "[]\n",
      "['Anytime', 'the', 'syntax', 'is', 'wrong,', 'this', 'gets', 'executed.']\n",
      "[]\n",
      "['With', 'that', 'we', 'wrap', 'a', 'short', 'day', '6!']\n",
      "['Tomorrow!!!']\n",
      "[]\n"
     ]
    }
   ],
   "source": [
    "#returns the lines as list of strings\n",
    "\n",
    "with open('Gaurav.txt', 'r') as file:\n",
    "    data = file.readlines()\n",
    "    print(data)\n",
    "    for i in data:\n",
    "        print(i.split())\n",
    "\n",
    "file.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "file = open('write.txt','w')\n",
    "file.write(\"This is write command\")\n",
    "file.write(\"\\nWrite in a the file\")\n",
    "file.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "This is write command\n",
      "\n",
      "Write in a the file\n"
     ]
    }
   ],
   "source": [
    "def readfile(k):\n",
    "    file = open('write.txt','r')\n",
    "    line = file.readline()\n",
    "\n",
    "    while line:\n",
    "        print(line)\n",
    "        line = file.readline()\n",
    "\n",
    "readfile(file)\n",
    "file.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hii,\n",
      "\n",
      "Hello\n",
      "\n",
      "How are you doing\n",
      "\n"
     ]
    }
   ],
   "source": [
    "file = open('other_file.txt', 'w')\n",
    "lst = ['Hii,\\n', 'Hello\\n', 'How are you doing\\n']\n",
    "file.writelines(lst)\n",
    "file.close()\n",
    "\n",
    "file = open('other_file.txt', 'r')\n",
    "def readfile(k):\n",
    "    file = open('other_file.txt','r')\n",
    "    line = file.readline()\n",
    "\n",
    "    while line:\n",
    "        print(line)\n",
    "        line = file.readline()\n",
    "\n",
    "readfile(file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "#renaming a file\n",
    "\n",
    "import os\n",
    "os.rename('write.txt', 'wrote.txt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "#deleting files\n",
    "\n",
    "file1 = open('new.txt', 'w')\n",
    "file1.write('new file')\n",
    "file1.close()\n",
    "os.remove('new.txt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
